import test from 'node:test';import assert from 'node:assert/strict';
import {jar,options} from './mock-headers.mjs';
import {adminSession,authorize,isOwner,sameOrigin,SESSION_COOKIE} from '../lib/server/auth.ts';
import {POST as login,DELETE as logout} from '../app/api/desk-65efdcc4b137b000/session/route.ts';
import {GET as list,POST as create} from '../app/api/desk-65efdcc4b137b000/entries/route.ts';
import {PUT as edit,DELETE as remove} from '../app/api/desk-65efdcc4b137b000/entries/[id]/route.ts';
import {POST as upload} from '../app/api/desk-65efdcc4b137b000/upload/route.ts';
import {GET as media} from '../app/api/media/[id]/route.ts';
import {newEntry} from '../lib/content.ts';
const id='11111111-1111-4111-8111-111111111111';const email='owner@example.test';const realFetch=fetch;
Object.assign(process.env,{SUPABASE_URL:'https://backend.example.test',SUPABASE_SERVICE_ROLE_KEY:'test-server-key',SUPABASE_ANON_KEY:'test-anon-key',ADMIN_USER_ID:id,ADMIN_EMAIL:email,SITE_URL:'https://portfolio.example.test'});
const owner={id,email,email_confirmed_at:'2026-01-01T00:00:00Z'};
function req(path,method='GET',body,origin='https://portfolio.example.test'){return new Request('https://portfolio.example.test'+path,{method,headers:{origin,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)})}
function stub(handler){globalThis.fetch=async(url,init)=>handler(String(url),init)}
test.after(()=>{globalThis.fetch=realFetch});
test.beforeEach(()=>{jar.clear();options.clear()});
test('owner authorization requires confirmed email AND immutable user ID',()=>{assert.ok(isOwner(owner));assert.equal(isOwner({...owner,id:'another-user'}),false);assert.equal(isOwner({...owner,email:'attacker@example.test'}),false);assert.equal(isOwner({...owner,email_confirmed_at:null}),false)});
test('CSRF rejects missing or hostile origins',()=>{assert.ok(sameOrigin(req('/api/desk-65efdcc4b137b000/entries','POST',{})));assert.equal(sameOrigin(req('/api/desk-65efdcc4b137b000/entries','POST',{},'https://attacker.test')),false);assert.equal(sameOrigin(new Request('https://portfolio.example.test/api/desk-65efdcc4b137b000/entries')),false)});
test('every write and draft listing requires verified authentication',async()=>{stub(()=>{throw new Error('Unauthenticated request must not access service')});const context={params:Promise.resolve({id})};for(const response of [await list(req('/api/desk-65efdcc4b137b000/entries')),await create(req('/api/desk-65efdcc4b137b000/entries','POST',{})),await edit(req('/api/desk-65efdcc4b137b000/entries/'+id,'PUT',{}),context),await remove(req('/api/desk-65efdcc4b137b000/entries/'+id,'DELETE',{}),context),await upload(req('/api/desk-65efdcc4b137b000/upload','POST',{}))])assert.equal(response.status,401)});
test('forged or expired cookies do not authorize',async()=>{jar.set(SESSION_COOKIE,'forged');stub(()=>Response.json({message:'expired'},{status:401}));assert.equal(await adminSession(),null);assert.equal((await authorize(req('/api/desk-65efdcc4b137b000/entries'))).status,401)});
test('valid auth on cross-site write still returns 403',async()=>{jar.set(SESSION_COOKIE,'valid-test-token');stub(()=>Response.json(owner));assert.equal((await authorize(req('/api/desk-65efdcc4b137b000/entries','POST',{},'https://attacker.test'),true)).status,403)});
test('login sets an HttpOnly, SameSite Strict cookie, never returns token',async()=>{stub(()=>Response.json({access_token:'test-access-token',expires_in:3600,user:owner}));const r=await login(req('/api/desk-65efdcc4b137b000/session','POST',{email,password:'test-only-password'}));assert.equal(r.status,200);assert.deepEqual(await r.json(),{ok:true});assert.equal(jar.get(SESSION_COOKIE),'test-access-token');assert.equal(options.get(SESSION_COOKIE).httpOnly,true);assert.equal(options.get(SESSION_COOKIE).sameSite,'strict')});
test('login rejects non-owner even with valid Supabase credentials',async()=>{stub(()=>Response.json({access_token:'other-token',user:{...owner,id:'other'}}));assert.equal((await login(req('/api/desk-65efdcc4b137b000/session','POST',{email,password:'test-only-password'}))).status,401);assert.equal(jar.size,0)});
test('draft media is private; public media is streamed with no cache and no sniff',async()=>{let published=false;const asset={id,object_key:id,filename:'chart.png',content_type:'image/png',size:3};stub(url=>{if(url.includes('/portfolio_assets?'))return Response.json([asset]);if(url.includes('/portfolio_entry_assets?'))return Response.json(published?[{entry_id:id,portfolio_entries:{data:{...newEntry('article'),coverUrl:'/api/media/'+id}}}]:[]);if(url.includes('/storage/'))return new Response(new Uint8Array([1,2,3]));throw new Error(url)});const context={params:Promise.resolve({id})};assert.equal((await media(req('/api/media/'+id),context)).status,404);published=true;const r=await media(req('/api/media/'+id),context);assert.equal(r.status,200);assert.equal(r.headers.get('X-Content-Type-Options'),'nosniff');assert.match(r.headers.get('Cache-Control'),/no-store/);assert.equal((await r.arrayBuffer()).byteLength,3)});
test('validated draft saves through transaction RPC and conflicts return 409',async()=>{jar.set(SESSION_COOKIE,'valid-test-token');const payload={...newEntry('article'),title:'Research',slug:'research'};let conflict=false;stub((url,init)=>{if(url.endsWith('/auth/v1/user'))return Response.json(owner);if(url.includes('rpc/portfolio_save_entry')){assert.equal(init.method,'POST');const body=JSON.parse(init.body);assert.deepEqual(body.asset_ids,[]);return conflict?Response.json({code:'40001',message:'Edit conflict'},{status:400}):Response.json({id,data:body.payload,revision:1,created_at:'2026-09-08',updated_at:'2026-09-08'})}throw new Error(url)});const r=await create(req('/api/desk-65efdcc4b137b000/entries','POST',payload));assert.equal(r.status,201);assert.equal((await r.json()).status,'draft');conflict=true;assert.equal((await edit(req('/api/desk-65efdcc4b137b000/entries/'+id,'PUT',{...payload,id,revision:1}),{params:Promise.resolve({id})})).status,409)});
test('logout clears session and rejects cross-origin requests',async()=>{assert.equal((await logout(req('/api/desk-65efdcc4b137b000/session','DELETE',undefined,'https://evil.test'))).status,403);jar.set(SESSION_COOKIE,'token');stub(()=>new Response(null,{status:204}));assert.equal((await logout(req('/api/desk-65efdcc4b137b000/session','DELETE'))).status,200);assert.equal(options.get(SESSION_COOKIE).maxAge,0)});
