'use client';

import {useRef,useState} from 'react';
import {Node,mergeAttributes} from '@tiptap/core';
import {NodeViewWrapper,ReactNodeViewRenderer,type NodeViewProps} from '@tiptap/react';
import katex from 'katex';
import {safeEmbed,safeRichUrl} from '@/lib/rich-content';

const safeUrl=(value:string)=>safeRichUrl(value);

export const FinanceImage=Node.create({
 name:'financeImage',group:'block',atom:true,draggable:true,
 addAttributes(){return{src:{default:''},alt:{default:''},caption:{default:''},href:{default:''},display:{default:'content'},width:{default:100}}},
 parseHTML(){return[{tag:'figure[data-finance-image]'},{tag:'img[src]',getAttrs:element=>({src:element.getAttribute('src'),alt:element.getAttribute('alt')||''})}]},
 renderHTML({HTMLAttributes}){return['figure',mergeAttributes(HTMLAttributes,{'data-finance-image':'','data-display':HTMLAttributes.display}),['img',{src:HTMLAttributes.src,alt:HTMLAttributes.alt,width:HTMLAttributes.width+'%'}],...(HTMLAttributes.caption?[['figcaption',{},HTMLAttributes.caption]]:[])]},
 addNodeView(){return ReactNodeViewRenderer(ImageView)}
});
function ImageView({node,updateAttributes,deleteNode,selected}:NodeViewProps){const picker=useRef<HTMLInputElement>(null);const [error,setError]=useState('');const a=node.attrs as Record<string,string|number>;return <NodeViewWrapper className={'rich-media-node '+(selected?'is-selected':'')} data-drag-handle><img src={String(a.src)} alt={String(a.alt)} style={{width:String(a.width)+'%'}}/><input aria-label="Image caption" placeholder="Add a caption" value={String(a.caption)} onChange={e=>updateAttributes({caption:e.target.value})}/><input hidden ref={picker} type="file" accept=".jpg,.jpeg,.png,.webp,.gif" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setError('');try{if(file.size>4194304)throw new Error('Maximum image size is 4 MB.');const response=await fetch('/api/desk-65efdcc4b137b000/upload',{method:'POST',headers:{'x-filename':encodeURIComponent(file.name),'Content-Type':'application/octet-stream'},body:file});const result=await response.json();if(!response.ok)throw new Error(result.error||'Replacement failed');updateAttributes({src:result.url})}catch(e){setError((e as Error).message)}}}/>{error&&<span role="alert">{error}</span>}<div className="rich-node-controls"><button type="button" onClick={()=>picker.current?.click()}>Replace image</button><button type="button" onClick={()=>{const alt=prompt('Describe this image for screen readers',String(a.alt));if(alt!==null)updateAttributes({alt})}}>Alt text</button><button type="button" onClick={()=>updateAttributes({display:a.display==='content'?'wide':a.display==='wide'?'full':'content'})}>{String(a.display)} width</button><button type="button" onClick={()=>{const href=prompt('Optional HTTPS link',String(a.href));if(href!==null)updateAttributes({href:safeUrl(href)})}}>Link</button><button type="button" onClick={()=>{const width=Number(prompt('Image width (25–100%)',String(a.width)));if(width>=25&&width<=100)updateAttributes({width})}}>Resize</button><button type="button" onClick={deleteNode}>Delete</button></div></NodeViewWrapper>}

export const Gallery=Node.create({
 name:'gallery',group:'block',atom:true,draggable:true,addAttributes(){return{images:{default:[]}}},parseHTML(){return[{tag:'div[data-gallery]',getAttrs:element=>{try{return{images:JSON.parse(element.getAttribute('data-images')||'[]')}}catch{return false}}}]},renderHTML({HTMLAttributes}){return['div',{'data-gallery':'','data-images':JSON.stringify(HTMLAttributes.images)}]},addNodeView(){return ReactNodeViewRenderer(GalleryView)}
});
function GalleryView({node,deleteNode,updateAttributes}:NodeViewProps){const images=(node.attrs.images||[]) as {src:string;alt:string;caption:string}[];return <NodeViewWrapper className="rich-gallery-node" data-drag-handle>{images.map((image,index)=><figure key={image.src+index}><img src={image.src} alt={image.alt}/><input aria-label={'Image '+(index+1)+' caption'} value={image.caption} onChange={e=>updateAttributes({images:images.map((item,i)=>i===index?{...item,caption:e.target.value}:item)})}/><input aria-label={'Image '+(index+1)+' alt text'} placeholder="Describe image" value={image.alt} onChange={e=>updateAttributes({images:images.map((item,i)=>i===index?{...item,alt:e.target.value}:item)})}/></figure>)}<button type="button" onClick={deleteNode}>Delete gallery</button></NodeViewWrapper>}

export const Callout=Node.create({name:'callout',group:'block',content:'block+',defining:true,draggable:true,addAttributes(){return{kind:{default:'takeaway'},title:{default:'Key Takeaway'}}},parseHTML(){return[{tag:'aside[data-callout]'}]},renderHTML({HTMLAttributes}){return['aside',mergeAttributes(HTMLAttributes,{'data-callout':HTMLAttributes.kind}),['strong',{'data-callout-title':''},HTMLAttributes.title],['div',0]]}});

function equationNode(name:string,inline:boolean){return Node.create({name,group:inline?'inline':'block',inline,atom:true,draggable:!inline,addAttributes(){return{latex:{default:''}}},parseHTML(){return[{tag:inline?'span[data-inline-equation]':'div[data-equation]',getAttrs:element=>({latex:element.getAttribute('data-latex')||''})}]},renderHTML({HTMLAttributes}){return[inline?'span':'div',{[inline?'data-inline-equation':'data-equation']:'','data-latex':HTMLAttributes.latex},HTMLAttributes.latex]},addNodeView(){return ReactNodeViewRenderer(EquationView)}})}
function EquationView({node,updateAttributes,deleteNode}:NodeViewProps){const latex=String(node.attrs.latex);let html='';try{html=katex.renderToString(latex,{displayMode:node.type.name==='equation',throwOnError:false,strict:'ignore',trust:false})}catch{}return <NodeViewWrapper as={node.type.name==='inlineEquation'?'span':'div'} className="rich-equation" contentEditable={false}><span dangerouslySetInnerHTML={{__html:html}}/><button type="button" aria-label="Edit equation" onClick={()=>{const value=prompt('LaTeX equation',latex);if(value!==null)updateAttributes({latex:value.slice(0,4000)})}}>Edit</button><button type="button" aria-label="Delete equation" onClick={deleteNode}>×</button></NodeViewWrapper>}
export const Equation=equationNode('equation',false);
export const InlineEquation=equationNode('inlineEquation',true);

export const Footnote=Node.create({name:'footnote',priority:1000,group:'inline',inline:true,atom:true,addAttributes(){return{text:{default:''}}},parseHTML(){return[{tag:'sup[data-footnote]',priority:1000,getAttrs:element=>({text:element.getAttribute('data-footnote-text')||''})}]},renderHTML({HTMLAttributes}){return['sup',{'data-footnote':'','data-footnote-text':HTMLAttributes.text},'†']},addNodeView(){return ReactNodeViewRenderer(FootnoteView)}});
function FootnoteView({node,updateAttributes,deleteNode}:NodeViewProps){return <NodeViewWrapper as="sup" className="rich-footnote" contentEditable={false}><button type="button" title={String(node.attrs.text)} onClick={()=>{const text=prompt('Footnote text',String(node.attrs.text));if(text===null)return;if(text.trim())updateAttributes({text:text.trim()});else deleteNode()}}>†</button></NodeViewWrapper>}

export const SafeEmbed=Node.create({name:'safeEmbed',group:'block',atom:true,draggable:true,addAttributes(){return{url:{default:''},provider:{default:''}}},parseHTML(){return[{tag:'div[data-safe-embed]',getAttrs:element=>({url:element.getAttribute('data-url')||'',provider:element.getAttribute('data-safe-embed')||''})}]},renderHTML({HTMLAttributes}){return['div',{'data-safe-embed':HTMLAttributes.provider,'data-url':HTMLAttributes.url}]},addNodeView(){return ReactNodeViewRenderer(EmbedView)}});
function EmbedView({node,deleteNode}:NodeViewProps){return <NodeViewWrapper className="rich-embed-node" contentEditable={false}><strong>{String(node.attrs.provider||'External')} embed</strong><a href={String(node.attrs.url)} target="_blank" rel="noreferrer">{String(node.attrs.url)}</a><button type="button" onClick={deleteNode}>Delete</button></NodeViewWrapper>}

export const AudioBlock=Node.create({name:'audio',group:'block',atom:true,draggable:true,addAttributes(){return{src:{default:''},title:{default:''},caption:{default:''}}},parseHTML(){return[{tag:'figure[data-audio]',getAttrs:element=>({src:element.getAttribute('data-src')||'',title:element.getAttribute('data-title')||'',caption:element.getAttribute('data-caption')||''})}]},renderHTML({HTMLAttributes}){return['figure',{'data-audio':'','data-src':HTMLAttributes.src,'data-title':HTMLAttributes.title,'data-caption':HTMLAttributes.caption}]},addNodeView(){return ReactNodeViewRenderer(AudioView)}});
function AudioView({node,updateAttributes,deleteNode}:NodeViewProps){return <NodeViewWrapper className="rich-audio-node" contentEditable={false}><input aria-label="Audio title" value={String(node.attrs.title)} placeholder="Audio title" onChange={e=>updateAttributes({title:e.target.value})}/><audio controls preload="metadata" src={String(node.attrs.src)}/><input aria-label="Audio caption" value={String(node.attrs.caption)} placeholder="Optional caption" onChange={e=>updateAttributes({caption:e.target.value})}/><button type="button" onClick={deleteNode}>Delete audio</button></NodeViewWrapper>}

export const TableOfContents=Node.create({name:'tableOfContents',group:'block',atom:true,draggable:true,parseHTML(){return[{tag:'nav[data-table-of-contents]'}]},renderHTML(){return['nav',{'data-table-of-contents':''},'Table of contents']},addNodeView(){return ReactNodeViewRenderer(()=> <NodeViewWrapper className="rich-toc-node" contentEditable={false}><strong>Table of contents</strong><span>Updates automatically from article headings.</span></NodeViewWrapper>)}});

export function supportedEmbed(value:string){const embed=safeEmbed(value);return embed?{url:value,provider:embed.kind}:null}
