'use client';
import {useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {Field} from '../admin-field';
import {emptySeo,researchTemplates,richText,slugify,type EntryInput,type RichDocument} from '@/lib/content';
import {parseDraft,isEntryDraft,DRAFT_PREFIX} from '@/lib/drafts';
import './research-editor.css';
const Editor=dynamic(()=>import('./research-editor'),{ssr:false,loading:()=> <p role="status">Opening writing desk…</p>});
const Preview=dynamic(()=>import('../entry-preview'),{loading:()=> <p role="status">Preparing preview…</p>});
const base='/api/desk-65efdcc4b137b000/entries';
async function request(url:string,method='GET',body?:unknown){const response=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Request failed. Your changes remain in the editor.');return result}
type Version={revision:number;createdAt:string;title:string;reason:string};
export default function ResearchComposer({initial}:{initial:EntryInput}){
 const router=useRouter();const[data,setData]=useState<EntryInput>({...initial,seo:{...emptySeo,...initial.seo}});const[status,setStatus]=useState('Saved');const[error,setError]=useState('');const[preview,setPreview]=useState(false);const[epoch,setEpoch]=useState(0);const[versions,setVersions]=useState<Version[]|null>(null);const[historyLoading,setHistoryLoading]=useState(false);const[versionPreview,setVersionPreview]=useState<EntryInput|null>(null);const[busy,setBusy]=useState(false);const[uploading,setUploading]=useState(false);const[recovery,setRecovery]=useState<EntryInput|null>(null);const[slugEdited,setSlugEdited]=useState(Boolean(initial.id));
 const destructive=useRef(false);
 const current=useRef(data),saved=useRef(JSON.stringify(data)),inFlight=useRef(false),generation=useRef(0),mounted=useRef(true),timer=useRef<ReturnType<typeof setTimeout>|null>(null);current.current=data;
 const changed=JSON.stringify(data)!==saved.current;
 const draftKey=useRef(DRAFT_PREFIX+'research:'+(initial.id||'new'));
 function edit(transform:(value:EntryInput)=>EntryInput){if(destructive.current)return;generation.current++;const next=transform(current.current);current.current=next;setData(next);setStatus('Unsaved changes')}
 useEffect(()=>{try{const stored=parseDraft(sessionStorage.getItem(draftKey.current),isEntryDraft);if(stored&&JSON.stringify(stored.value)!==saved.current)setRecovery({...stored.value,seo:{...emptySeo,...stored.value.seo}})}catch{}},[]);
 useEffect(()=>{if(!changed)return;try{sessionStorage.setItem(draftKey.current,JSON.stringify({version:1,updatedAt:new Date().toISOString(),value:data}))}catch{}},[data,changed]);
 const update=<K extends keyof EntryInput>(key:K,value:EntryInput[K])=>{edit(d=>({...d,[key]:value}))};
 async function save(mode:'draft'|'publish'|'unpublish'='draft'){
  if(inFlight.current||uploading)return;inFlight.current=true;setBusy(true);setStatus('Saving…');setError('');const snapshot=current.current;const before=JSON.stringify(snapshot);const gen=generation.current;
  const title=snapshot.title.trim()||'Untitled research';const slug=snapshot.slug||slugify(title)+'-'+crypto.randomUUID().slice(0,8);
  try{const result:EntryInput=await request(snapshot.id?base+'/'+snapshot.id:base,snapshot.id?'PUT':'POST',{...snapshot,title,slug,tags:[...new Map(snapshot.tags.map(t=>[t.trim().toLowerCase(),t.trim()])).values()].filter(Boolean),saveMode:mode,status:mode==='publish'?'published':mode==='unpublish'?'draft':snapshot.status});
   if(!mounted.current)return;
   const same=generation.current===gen&&JSON.stringify(current.current)===before;
   const next=same?result:{...current.current,id:result.id,revision:result.revision,status:result.status,slug:current.current.slug||result.slug};
   saved.current=JSON.stringify(result);current.current=next;setData(next);setStatus(same?(mode==='publish'?'Published. Your changes are live.':'Saved privately'):'Unsaved changes');
   if(!snapshot.id&&result.id){window.history.replaceState(null,'','/desk-65efdcc4b137b000/editor/'+result.id);try{sessionStorage.removeItem(draftKey.current)}catch{}draftKey.current=DRAFT_PREFIX+'research:'+result.id;}
   try{if(same)sessionStorage.removeItem(draftKey.current);else sessionStorage.setItem(draftKey.current,JSON.stringify({version:1,updatedAt:new Date().toISOString(),value:next}))}catch{}
   if(mode!=='draft')router.refresh();
  }catch(e){if(mounted.current){setError((e as Error).message);setStatus('Save failed')}}finally{inFlight.current=false;if(mounted.current)setBusy(false)}
 }
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
 useEffect(()=>{if(!changed||busy||uploading||recovery||status==='Save failed')return;timer.current=setTimeout(()=>{void save('draft')},1800);return()=>{if(timer.current)clearTimeout(timer.current)}},[data,busy,uploading,recovery,changed,status]);
 useEffect(()=>{if(!changed&&!busy&&!uploading)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[changed,busy,uploading]);
 useEffect(()=>{const guard=(event:MouseEvent)=>{if(event.defaultPrevented||!(current.current&&JSON.stringify(current.current)!==saved.current||inFlight.current))return;const target=event.target instanceof Element?event.target.closest('a[href]'):null;if(!target||target.getAttribute('href')?.startsWith('#')||target.getAttribute('target')==='_blank')return;if(!confirm('You have unsaved changes. Leave this editor? A recovery copy will remain in this tab.')){event.preventDefault();event.stopPropagation()}};document.addEventListener('click',guard,true);return()=>document.removeEventListener('click',guard,true)},[]);
 async function loadVersions(){if(!current.current.id)return;setError('');setHistoryLoading(true);try{setVersions(await request(base+'/'+current.current.id+'/versions'))}catch(e){setError((e as Error).message)}finally{setHistoryLoading(false)}}
 async function restore(version:Version){if(!data.id||busy||!confirm('Restore this version into your private draft? Your live article and version history are preserved.'))return;destructive.current=true;inFlight.current=true;setBusy(true);setStatus('Restoring version…');setError('');try{const result=await request(base+'/'+data.id+'/versions/'+version.revision+'/restore','POST',{currentRevision:data.revision});generation.current++;saved.current=JSON.stringify(result);current.current=result;setData(result);try{sessionStorage.removeItem(draftKey.current)}catch{}setEpoch(v=>v+1);setVersionPreview(null);setStatus('Version restored to draft');await loadVersions()}catch(e){setError((e as Error).message);setStatus('Restore failed')}finally{destructive.current=false;inFlight.current=false;setBusy(false)}}
 function template(id:string){const selected=researchTemplates.find(t=>t.id===id);if(!selected)return;if((data.body||data.richContent?.content?.some(n=>n.type!=='paragraph'||n.content?.length))&&!confirm('Replace the current draft content with this template? Save a version first if you want to keep the current structure.'))return;const doc=structuredClone(selected.content);edit(d=>({...d,contentFormat:'rich',richContent:doc,body:richText(doc)}));setEpoch(v=>v+1);setStatus('Unsaved changes')}
 async function cover(file:File){setError('');if(file.size>4*1024*1024){setError('Images must be no larger than 4 MB.');return}setUploading(true);setStatus('Uploading image…');try{const response=await fetch('/api/desk-65efdcc4b137b000/upload',{method:'POST',headers:{'x-filename':encodeURIComponent(file.name),'Content-Type':'application/octet-stream'},body:file});const result=await response.json();if(!response.ok)throw new Error(result.error||'Upload failed');update('coverUrl',result.url)}catch(e){setError((e as Error).message);setStatus('Upload failed')}finally{setUploading(false)}}
 return <section className="research-composer"><header className="composer-header"><Link href="/desk-65efdcc4b137b000">← Publishing desk</Link><div className="composer-actions"><span role="status" aria-live="polite">{status}</span><button type="button" className="button secondary" disabled={busy||uploading} onClick={()=>void save('draft')}>Save draft</button><button type="button" className="button secondary" onClick={()=>setPreview(v=>!v)}>{preview?'Write':'Preview'}</button><button type="button" className="button" disabled={busy||uploading||!data.title.trim()} onClick={()=>void save('publish')}>{data.status==='published'?'Republish':'Publish'}</button></div></header>
 {recovery&&<div role="status" className="composer-hint">Unsaved writing was recovered from this tab. <button type="button" onClick={()=>{edit(()=>({...recovery,id:data.id,revision:data.revision,status:data.status}));setEpoch(v=>v+1);setRecovery(null)}}>Restore recovered writing</button> <button type="button" onClick={()=>{setRecovery(null);try{sessionStorage.removeItem(draftKey.current)}catch{}}}>Keep server version</button></div>}
 {error&&<p className="form-error" role="alert">{error} <button type="button" onClick={()=>void save('draft')}>Retry save</button></p>}
 {data.status==='published'&&<p className="composer-hint">Your published article stays unchanged until you click Republish.</p>}
 <div className="composer-title"><Field label="Article title"><input value={data.title} placeholder="Your research title" maxLength={180} onChange={e=>{const title=e.target.value;edit(d=>({...d,title,slug:!slugEdited&&d.status!=='published'?slugify(title):d.slug}))}}/></Field><Field label="Subtitle"><textarea rows={2} value={data.excerpt} placeholder="A short introduction to your research" maxLength={800} onChange={e=>update('excerpt',e.target.value)}/></Field></div>
 {!preview&&<div className="composer-tools"><label>Start from a template <select value="" onChange={e=>template(e.target.value)}><option value="">Choose structure…</option>{researchTemplates.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label>{data.id&&<button type="button" disabled={historyLoading} onClick={()=>void loadVersions()}>{historyLoading?'Loading history…':'Version history'}</button>}{data.id&&<button type="button" disabled={busy||changed} onClick={async()=>{try{await request(base+'/'+data.id+'/versions','POST',{revision:data.revision});setStatus('Version saved');await loadVersions()}catch(e){setError((e as Error).message)}}}>Save version</button>}</div>}
 {preview&&<Preview {...data}/>}<div hidden={preview}><Editor disabled={destructive.current} key={epoch} value={data.richContent as RichDocument|null} legacyMarkdown={data.body} onChange={(richContent,body)=>{edit(d=>({...d,contentFormat:'rich',richContent,body}))}}/></div>
 <details className="composer-settings"><summary>Article details & publishing settings</summary><div className="composer-settings-grid"><Field label="Author"><input value={data.author} maxLength={100} onChange={e=>update('author',e.target.value)}/></Field><Field label="Publication date"><input type="date" value={data.date} onChange={e=>update('date',e.target.value)}/></Field><Field label="URL slug" hint="Published URLs stay unchanged when you edit the title."><input value={data.slug} maxLength={140} onChange={e=>{setSlugEdited(true);update('slug',e.target.value)}}/></Field><Field label="Category"><input value={data.category} maxLength={80} onChange={e=>update('category',e.target.value)}/></Field><Field label="Tags" hint="Separate tags with commas. Duplicate tags are merged on save."><input value={data.tags.join(',')} onChange={e=>update('tags',e.target.value.split(','))}/></Field><Field label="Cover image"><input type="file" accept=".jpg,.jpeg,.png,.webp,.gif" onChange={e=>{const file=e.target.files?.[0];if(file)void cover(file);e.target.value=''}}/></Field><Field label="Cover alt text"><input value={data.coverAlt} maxLength={220} onChange={e=>update('coverAlt',e.target.value)}/></Field>{data.coverUrl&&<div><img className="cover-preview" src={data.coverUrl} alt={data.coverAlt}/><button type="button" onClick={()=>update('coverUrl','')}>Remove cover</button></div>}<label><input type="checkbox" checked={data.featured} onChange={e=>update('featured',e.target.checked)}/> Feature on home page</label></div>
 <h2>Search & social preview</h2><div className="composer-settings-grid">{(['title','description','canonicalUrl','socialImageUrl','openGraphTitle','openGraphDescription'] as const).map(key=><Field key={key} label={{title:'SEO title',description:'Meta description',canonicalUrl:'Canonical URL',socialImageUrl:'Social image URL',openGraphTitle:'Open Graph title',openGraphDescription:'Open Graph description'}[key]}><input value={data.seo[key]} placeholder={key==='title'||key==='openGraphTitle'?data.title:key==='description'||key==='openGraphDescription'?data.excerpt:''} onChange={e=>update('seo',{...data.seo,[key]:e.target.value})}/></Field>)}</div><div className="composer-social-preview">{(data.seo.socialImageUrl||data.coverUrl)&&<img src={data.seo.socialImageUrl||data.coverUrl} alt="Social preview"/>}<small>baselalghamdi.me</small><h3>{data.seo.openGraphTitle||data.seo.title||data.title}</h3><p>{data.seo.openGraphDescription||data.seo.description||data.excerpt}</p></div>
 {data.status==='published'&&<button type="button" disabled={busy||uploading} onClick={()=>{if(confirm('Unpublish this article? It will become private.'))void save('unpublish')}}>Unpublish article</button>}
 {data.id&&<button type="button" className="delete-button" disabled={busy||uploading} onClick={async()=>{if(inFlight.current||!confirm('Delete this article permanently?'))return;destructive.current=true;inFlight.current=true;setBusy(true);try{await request(base+'/'+data.id,'DELETE',{revision:data.revision});saved.current=JSON.stringify(current.current);try{sessionStorage.removeItem(draftKey.current)}catch{}router.push('/desk-65efdcc4b137b000');router.refresh()}catch(e){setError((e as Error).message);destructive.current=false;inFlight.current=false;setBusy(false)}}}>Delete article</button>}
 </details>
 {versions&&<section className="composer-versions"><h2>Version history</h2><button type="button" onClick={()=>{setVersions(null);setVersionPreview(null)}}>Close history</button>{versions.length===0&&<p>No earlier versions yet.</p>}{versions.map(v=><div key={v.revision}><span>{new Date(v.createdAt).toLocaleString()} · {v.reason}</span><button type="button" onClick={async()=>{try{setVersionPreview(await request(base+'/'+data.id+'/versions/'+v.revision))}catch(e){setError((e as Error).message)}}}>Preview version</button><button type="button" disabled={busy||uploading} onClick={()=>void restore(v)}>Restore to draft</button></div>)}{versionPreview&&<Preview {...versionPreview}/>}</section>}
 </section>
}
