import {pageMetadata} from '@/lib/server/seo';
export const metadata=pageMetadata('/','Research & Projects','Financial research, valuation models, and projects by Basel Alghamdi.');
import Link from 'next/link';
import {ArrowRight,ArrowUpRight} from 'lucide-react';
import {listEntries,getProfile} from '@/lib/server/data';
import {displayDate,entryLink} from '@/lib/content';
import {ArticleCard,ProjectRow} from '@/components/portfolio';
export const dynamic='force-dynamic';
export default async function Home(){const [articles,projects,p]=await Promise.all([listEntries('article'),listEntries('project'),getProfile()]);const featured=articles[0];return <main id="main-content">
<section className="intro wrap"><div><p className="eyebrow">FINANCE · RESEARCH · VALUATION</p><h1>{p.name}<span className="title-period">.</span></h1></div><div className="intro-note"><p>{p.intro}</p><Link className="text-link" href="/about">A little about me <ArrowUpRight size={16}/></Link></div></section>
<section className="wrap" aria-label="Featured research">{featured?<Link className={'featured-story '+(!featured.coverUrl?'no-cover':'')} href={entryLink(featured)}><div className="featured-copy"><p className="eyebrow">THE LATEST RESEARCH</p><div><p className="feature-category">{featured.category}</p><h2>{featured.title}</h2><p className="feature-description">{featured.excerpt}</p></div><div className="feature-bottom"><span>{displayDate(featured.date)}{featured.readingMinutes?` · ${featured.readingMinutes} MIN READ`:null}</span><span className="round-arrow"><ArrowUpRight size={24}/></span></div></div>{featured.coverUrl&&<div className="feature-image"><img src={featured.coverUrl} alt={featured.coverAlt} fetchPriority="high"/></div>}</Link>:<div className="journal-empty"><p className="eyebrow">THE RESEARCH JOURNAL</p><h2>Research & perspectives.</h2><p>No research published yet.</p><Link className="text-link" href="/about">Meet the author <ArrowUpRight size={16}/></Link></div>}</section>
<section className="wrap home-section"><div className="section-heading"><div className="heading-group"><span className="section-index">01</span><h2>The research journal</h2></div><Link className="text-link" href="/research">All research <ArrowRight size={16}/></Link></div>{articles.length?<div className="article-grid">{articles.slice(articles.length>1?1:0,3).map(a=><ArticleCard key={a.id} article={a}/>)}</div>:<p className="muted">Published research will appear here.</p>}</section>
<section className="projects-band"><div className="wrap home-section"><div className="section-heading"><div className="heading-group"><span className="section-index">02</span><h2>Selected projects</h2></div><Link className="text-link" href="/projects">All projects <ArrowRight size={16}/></Link></div><p className="section-description">Financial models, reports, presentations, and other work.</p>{projects.length?<div className="project-list">{projects.slice(0,4).map((e,i)=><ProjectRow key={e.id} project={e} index={i}/>)}</div>:<p className="muted">No projects published yet.</p>}</div></section>
<section className="about-strip wrap"><div><p className="eyebrow">THE PERSON BEHIND THE RESEARCH</p><h2>Learning through the work.</h2><p>{p.intro}</p><Link className="text-link" href="/about">More about me <ArrowUpRight size={16}/></Link></div><div className="education-mini"><span>{p.university}</span><strong>{p.degree}</strong></div></section></main>}
