'use client';
import {AdminLogout} from './admin-login';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';import {useRouter} from 'next/navigation';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {kinds,kindLabels,slugify,entryLink,displayDate,type Entry,type EntryInput,type Profile} from '@/lib/content';
import {renderMarkdown} from '@/lib/markdown';
async function api(url:string,method:string,body?:unknown){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||'The request failed.');return data}
function useUnsaved(dirty:boolean){useEffect(()=>{if(!dirty)return;const f=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f)},[dirty])}
export function Field({label,children,hint}:{label:string;children:React.ReactNode;hint?:string}){return <label className="admin-field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function AdminDashboard({entries,profile}:{entries:Entry[];profile:Profile}){const[query,setQuery]=useState('');return <><div className="admin-topbar"><div><p className="eyebrow">YOUR PUBLISHING DESK</p><h1>Content & portfolio.</h1></div><div className="admin-actions"><Link className="button secondary" href="/">View site</Link><a className="button secondary" href="/api/desk-65efdcc4b137b000/export">Export content</a><AdminLogout/></div></div><Tabs defaultValue="article" className="admin-tabs"><TabsList>{kinds.map(k=><TabsTrigger value={k} key={k}>{kindLabels[k]} <span className="tab-count">{entries.filter(e=>e.kind===k).length}</span></TabsTrigger>)}<TabsTrigger value="profile">About & contact</TabsTrigger></TabsList>{kinds.map(k=><TabsContent value={k} key={k}><div className="admin-list-heading"><Field label="Search content"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search titles…"/></Field><Link className="button" href={'/desk-65efdcc4b137b000/editor/new?kind='+k}>Add {k==='article'?'research':k==='honor'?'academic honor':k}</Link></div><div className="admin-entry-list">{entries.filter(e=>e.kind===k&&e.title.toLowerCase().includes(query.toLowerCase())).map(e=><div className="admin-entry" key={e.id}><div><span className={'status-tag '+e.status}>{e.status}</span><h2><Link href={'/desk-65efdcc4b137b000/editor/'+e.id}>{e.title}</Link></h2><p>{e.category||e.issuer} {e.date?'· '+displayDate(e.date):''}</p></div><div className="admin-actions"><Link className="text-link" href={'/desk-65efdcc4b137b000/editor/'+e.id}>Edit</Link>{e.status==='published'&&<Link className="text-link" href={entryLink(e)}>View</Link>}</div></div>)}</div>{!entries.some(e=>e.kind===k)&&<div className="empty-result"><h2>Your {kindLabels[k].toLowerCase()} start here.</h2><p>Add your own work, save a draft, and publish when it’s ready.</p></div>}</TabsContent>)}<TabsContent value="profile"><ProfileEditor initial={profile}/></TabsContent></Tabs></>}
export function EntryEditor({initial}:{initial:EntryInput}){const router=useRouter();const[data,setData]=useState(initial);const[saved,setSaved]=useState(JSON.stringify(initial));const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');const body=useRef<HTMLTextAreaElement>(null);const dirty=JSON.stringify(data)!==saved;useUnsaved(dirty);
function update<K extends keyof EntryInput>(key:K,value:EntryInput[K]){setData(d=>({...d,[key]:value}));setMessage('')}
function insert(before:string,after=''){const el=body.current;const start=el?.selectionStart??data.body.length;const end=el?.selectionEnd??start;update('body',data.body.slice(0,start)+before+data.body.slice(start,end)+after+data.body.slice(end));requestAnimationFrame(()=>{el?.focus();el?.setSelectionRange(start+before.length,end+before.length)})}
async function save(){setBusy(true);setError('');setMessage('');try{const result=await api(data.id?'/api/desk-65efdcc4b137b000/entries/'+data.id:'/api/desk-65efdcc4b137b000/entries',data.id?'PUT':'POST',{...data,tags:data.tags.map(t=>t.trim()).filter(Boolean)});setData(result);setSaved(JSON.stringify(result));setMessage(result.status==='published'?'Published. Your changes are live.':'Draft saved. Only you can see it.');if(!data.id)router.replace('/desk-65efdcc4b137b000/editor/'+result.id);router.refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function upload(file:File,mode:'cover'|'body'|'attachment'){setBusy(true);setError('');try{if(file.size>4*1024*1024)throw new Error('Maximum upload size is 4 MB. For larger documents, add a secure HTTPS download link.');const r=await fetch('/api/desk-65efdcc4b137b000/upload',{method:'POST',headers:{'x-filename':encodeURIComponent(file.name),'Content-Type':'application/octet-stream'},body:file});const f=await r.json();if(!r.ok)throw new Error(f.error||'Upload failed.');if(mode==='cover'){setData(d=>({...d,coverUrl:f.url}));}else if(mode==='body'){insert('\n\n![Describe this image]('+f.url+')\n\n')}else setData(d=>({...d,attachments:[...d.attachments,{url:f.url,name:f.name,format:f.format}]}));setMessage('File uploaded. Save the entry to attach it.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
const credential=data.kind==='certificate'||data.kind==='honor';const preview=renderMarkdown(data.body);
return <><div className="admin-topbar"><div><a href="/desk-65efdcc4b137b000" className="text-link" onClick={e=>{if(dirty&&!window.confirm('Leave without saving your changes?'))e.preventDefault()}}>Back to publishing desk</a><h1>{initial.id?'Edit':'New'} {data.kind==='article'?'research':data.kind==='honor'?'academic honor':data.kind}</h1></div><span className="muted">{dirty?'Unsaved changes':data.id?'Saved':'Not saved yet'}</span></div><form onSubmit={e=>{e.preventDefault();void save()}} className="editor-grid"><fieldset disabled={busy} className="editor-main"><Field label="Title"><input required maxLength={180} value={data.title} onChange={e=>setData(d=>({...d,title:e.target.value,...(!d.id&&(!d.slug||d.slug===slugify(d.title))?{slug:slugify(e.target.value)}:{})}))}/></Field><Field label="URL slug" hint="This becomes the address of your published page."><input required value={data.slug} onChange={e=>update('slug',e.target.value)} maxLength={140}/></Field><Field label={credential?'Description':'Short summary'}><textarea rows={3} maxLength={800} value={data.excerpt} onChange={e=>update('excerpt',e.target.value)}/></Field>
{credential&&<><Field label="Issuing organization"><input value={data.issuer} onChange={e=>update('issuer',e.target.value)}/></Field><Field label="Credential link"><input type="url" placeholder="https://" value={data.credentialUrl} onChange={e=>update('credentialUrl',e.target.value)}/></Field></>}
{!credential&&<Tabs defaultValue="write"><TabsList><TabsTrigger value="write">Write</TabsTrigger><TabsTrigger value="preview">Preview article</TabsTrigger></TabsList><TabsContent value="write"><div className="editor-toolbar" aria-label="Formatting"><button type="button" onClick={()=>insert('\n## ')}>Heading 2</button><button type="button" onClick={()=>insert('\n### ')}>Heading 3</button><button type="button" onClick={()=>insert('**','**')}>Bold</button><button type="button" onClick={()=>insert('\n> ')}>Quote</button><button type="button" onClick={()=>insert('[','](https://)')}>Link</button><button type="button" onClick={()=>insert('\n\n| Metric | Value |\n| --- | --- |\n|  |  |\n')}>Table</button></div><Field label="Content" hint="Write in Markdown. Heading 2 and Heading 3 automatically build “In this article”."><textarea ref={body} dir="auto" className="body-editor" rows={22} maxLength={160000} value={data.body} onChange={e=>update('body',e.target.value)}/></Field><Field label="Insert an image in the article"><input type="file" accept=".jpg,.jpeg,.png,.webp,.gif" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,'body');e.target.value=''}}/></Field></TabsContent><TabsContent value="preview"><div className="article-body editor-preview"><h1>{data.title||'Untitled'}</h1><p>{data.excerpt}</p>{preview.toc.length>0&&<nav className="preview-toc"><strong>In this article</strong>{preview.toc.map(t=><a key={t.id} href={'#'+t.id}>{t.label}</a>)}</nav>}<div dir="auto" dangerouslySetInnerHTML={{__html:preview.html}}/></div></TabsContent></Tabs>}
</fieldset><fieldset disabled={busy} className="editor-sidebar"><div className="editor-panel"><h2>Publishing</h2><div className="admin-field"><label htmlFor="publish-status">Visibility</label><Select value={data.status} onValueChange={v=>update('status',v as 'draft'|'published')}><SelectTrigger id="publish-status"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="draft">Draft, only you</SelectItem><SelectItem value="published">Published, everyone</SelectItem></SelectContent></Select></div><Field label="Date"><input type="date" value={data.date} onChange={e=>update('date',e.target.value)}/></Field><Field label="Category"><input value={data.category} onChange={e=>update('category',e.target.value)} maxLength={80}/></Field><Field label="Display order" hint="Lower numbers appear first."><input type="number" min={0} max={9999} value={data.sortOrder} onChange={e=>update('sortOrder',Number(e.target.value))}/></Field>{!credential&&<><label className="checkbox-field"><Checkbox checked={data.featured} onCheckedChange={v=>update('featured',v===true)}/>Feature on the home page</label><Field label="Tags" hint="Separate with commas."><input value={data.tags.join(', ')} onChange={e=>update('tags',e.target.value.split(',').map(x=>x.trim()))}/></Field></>}<button className="button" type="submit">{busy?'Saving…':'Save '+(data.status==='published'?'& publish':'draft')}</button><div role="status" className="save-feedback">{message}</div>{error&&<p role="alert" className="form-error">{error}</p>}</div>
<div className="editor-panel"><h2>{credential?'Certificate image':'Cover image'}</h2>{data.coverUrl&&<img className="cover-preview" src={data.coverUrl} alt={data.coverAlt||'Uploaded image preview'}/>}<Field label="Upload image" hint="JPG, PNG, WebP, GIF. Up to 4 MB."><input type="file" accept=".jpg,.jpeg,.png,.webp,.gif" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,'cover');e.target.value=''}}/></Field><Field label="Image URL"><input value={data.coverUrl} onChange={e=>update('coverUrl',e.target.value)} placeholder="https:// or uploaded file"/></Field><Field label="Image description" hint="Describe the image for readers using screen readers."><input value={data.coverAlt} onChange={e=>update('coverAlt',e.target.value)} maxLength={220}/></Field>{data.coverUrl&&<button type="button" className="text-link" onClick={()=>update('coverUrl','')}>Remove image</button>}</div>
{!credential&&<div className="editor-panel"><h2>Supporting files</h2><Field label="Upload a file" hint="PDF, XLSX, PPTX. Up to 4 MB each."><input type="file" accept=".pdf,.xlsx,.pptx" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,'attachment');e.target.value=''}}/></Field>{data.attachments.map((f,i)=><div className="attachment-edit" key={i}><Field label="File name"><input value={f.name} onChange={e=>update('attachments',data.attachments.map((v,n)=>n===i?{...v,name:e.target.value}:v))}/></Field><Field label="Download URL"><input value={f.url} onChange={e=>update('attachments',data.attachments.map((v,n)=>n===i?{...v,url:e.target.value}:v))}/></Field><Field label="Format"><input value={f.format} onChange={e=>update('attachments',data.attachments.map((v,n)=>n===i?{...v,format:e.target.value.toUpperCase()}:v))}/></Field><button type="button" className="text-link" onClick={()=>update('attachments',data.attachments.filter((_,n)=>n!==i))}>Remove file</button></div>)}{data.attachments.length<10&&<button type="button" className="button secondary" onClick={()=>update('attachments',[...data.attachments,{url:'',name:'',format:'PDF'}])}>Add external file link</button>}</div>}
{data.id&&<AlertDialog><AlertDialogTrigger className="button delete-button" type="button">Delete entry</AlertDialogTrigger><AlertDialogContent><AlertDialogTitle>Delete this entry?</AlertDialogTitle><AlertDialogDescription>This removes the entry from your portfolio. This cannot be undone.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep entry</AlertDialogCancel><AlertDialogAction onClick={async()=>{setBusy(true);try{await api('/api/desk-65efdcc4b137b000/entries/'+data.id,'DELETE',{revision:data.revision});setSaved(JSON.stringify(data));router.push('/desk-65efdcc4b137b000');router.refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Delete entry</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
</fieldset></form></>}
function ProfileEditor({initial}:{initial:Profile}){const[p,setP]=useState(initial);const[saved,setSaved]=useState(JSON.stringify(initial));const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');useUnsaved(JSON.stringify(p)!==saved);const fields=['name','intro','bio','university','degree','faculty','location','email','linkedin'] as const;const labels={name:'Display name',intro:'Introduction',bio:'About you',university:'University',degree:'Degree / major',faculty:'Faculty',location:'Location',email:'Contact email',linkedin:'LinkedIn URL'};return <form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await api('/api/desk-65efdcc4b137b000/profile','PUT',p);setP(r);setSaved(JSON.stringify(r));setMessage('Profile saved.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><fieldset disabled={busy} className="profile-form">{fields.map(k=><Field label={labels[k]} key={k}>{k==='bio'||k==='intro'?<textarea rows={k==='bio'?8:3} value={p[k]} onChange={e=>setP({...p,[k]:e.target.value})}/>:<input type={k==='email'?'email':k==='linkedin'?'url':'text'} value={p[k]} onChange={e=>setP({...p,[k]:e.target.value})}/>}</Field>)}<Field label="Interests" hint="One interest per line."><textarea rows={5} value={p.interests.join('\n')} onChange={e=>setP({...p,interests:e.target.value.split('\n')})}/></Field><button className="button" type="submit">{busy?'Saving…':'Save profile'}</button><p role="status">{message}</p>{error&&<p role="alert" className="form-error">{error}</p>}</fieldset></form>}
