'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {checksum,decodeFile,MAX_BACKUP_BYTES,restoreEntry,validateBackup,type Backup} from '@/lib/backup';
import type {Profile} from '@/lib/content';
const API='/api/desk-65efdcc4b137b000';
async function responseJson(response:Response){const data=await response.json();if(!response.ok)throw new Error(data.error||'The backup request failed.');return data}
function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function BackupTools({profile}:{profile:Profile}){const router=useRouter();const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[backup,setBackup]=useState<Backup|null>(null);
async function exportAll(){setBusy(true);setMessage('Preparing backup…');try{const manifest=await responseJson(await fetch(API+'/export',{cache:'no-store'}));let total=new TextEncoder().encode(JSON.stringify(manifest)).length;for(const collection of ['entries','assets']){let after:string|null=null;const seen=new Set<string>();do{const page=await responseJson(await fetch(API+'/export?collection='+collection+(after?'&after='+encodeURIComponent(after):''),{cache:'no-store'}));total+=new TextEncoder().encode(JSON.stringify(page.items)).length;if(total>MAX_BACKUP_BYTES)throw new Error('Backup exceeds the 64 MB browser limit. No incomplete backup was downloaded.');manifest[collection].push(...page.items);after=page.next;if(after){if(seen.has(after))throw new Error('Backup cursor did not advance. Please try again.');seen.add(after)}setMessage('Preparing '+manifest[collection].length+' '+collection+'…')}while(after)}const assets=[];for(const a of manifest.assets){setMessage('Backing up file '+(assets.length+1)+' of '+manifest.assets.length+'…');const r=await fetch('/api/media/'+a.id,{cache:'no-store'});if(!r.ok)throw new Error('Could not back up '+a.filename+'. No incomplete backup was downloaded.');const bytes=new Uint8Array(await r.arrayBuffer());total+=Math.ceil(bytes.length/3)*4;if(total>MAX_BACKUP_BYTES)throw new Error('Backup exceeds the 64 MB browser limit. No incomplete backup was downloaded.');let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));assets.push({...a,base64:btoa(binary),sha256:await checksum(bytes)})}const complete={...manifest,assets};await validateBackup(complete);if(new Blob([JSON.stringify(complete)]).size>MAX_BACKUP_BYTES)throw new Error('Backup exceeds the 64 MB browser limit. No incomplete backup was downloaded.');download(complete,'portfolio-backup-'+new Date().toISOString().slice(0,10)+'.json');setMessage('Complete backup downloaded, including uploaded files and profile. External HTTPS files remain links.')}catch(e){setMessage(e instanceof Error?e.message:'Backup failed.')}finally{setBusy(false)}}
async function inspect(file:File){setBusy(true);setBackup(null);try{if(file.size>MAX_BACKUP_BYTES)throw new Error('Choose a backup up to 64 MB.');const verified=await validateBackup(JSON.parse(await file.text()));setBackup(verified);setMessage('Validated '+verified.entries.length+' entries and '+verified.assets.length+' files. Existing content will remain unchanged.')}catch(e){setMessage(e instanceof Error?e.message:'Invalid backup.')}finally{setBusy(false)}}
async function restore(){if(!backup||!confirm('Import '+backup.entries.length+' entries as new drafts? Existing content will remain unchanged.'))return;setBusy(true);let saved=0;try{await validateBackup(backup);const ids=new Map<string,string>();for(const a of backup.assets){setMessage('Restoring file '+(ids.size+1)+' of '+backup.assets.length+'…');const result=await responseJson(await fetch(API+'/upload',{method:'POST',headers:{'x-filename':encodeURIComponent(a.filename)},body:decodeFile(a.base64) as BodyInit}));ids.set(a.id,result.id)}const suffix=crypto.randomUUID().slice(0,8);for(const entry of backup.entries){await responseJson(await fetch(API+'/entries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(restoreEntry(entry,ids,suffix+'-'+saved.toString(36)))}));saved++;setMessage('Restored '+saved+' of '+backup.entries.length+' drafts…')}setMessage('Restored '+saved+' draft copies. Review them before publishing.');setBackup(null);router.refresh()}catch(e){setMessage('Restore stopped after '+saved+' entries. Already imported drafts remain; review them before retrying. '+(e instanceof Error?e.message:''));router.refresh()}finally{setBusy(false)}}
async function restoreProfile(){if(!backup||!confirm('Replace About and contact details with the backup profile for '+backup.profile.name+' ('+backup.profile.email+')?'))return;setBusy(true);try{await responseJson(await fetch(API+'/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...backup.profile,revision:profile.revision})}));setMessage('Profile restored.');router.refresh()}catch(e){setMessage(e instanceof Error?e.message:'Profile could not be restored.')}finally{setBusy(false)}}
return <details className="backup-tools"><summary>Backup & restore</summary><p>Download your content, profile, and uploaded files. Imports create draft copies; profile restoration is a separate action.</p><div className="admin-actions"><button className="button secondary" disabled={busy} onClick={exportAll}>Download complete backup</button><label className="button secondary">Choose backup<input type="file" accept="application/json,.json" disabled={busy} className="sr-only" onChange={e=>{const file=e.target.files?.[0];if(file)void inspect(file);e.target.value=''}}/></label></div>{backup&&<div><p>Backup profile: {backup.profile.name} · {backup.profile.email}</p><div className="admin-actions"><button className="button" disabled={busy} onClick={restore}>Import as draft copies</button><button className="button secondary" disabled={busy} onClick={restoreProfile}>Restore About & contact</button></div></div>}<p role="status" aria-live="polite">{message}</p></details>}
