import {z} from 'zod';
import {entryInput,profileInput} from './validation';
import {inspectUpload} from './uploads';
export const MAX_BACKUP_BYTES=64*1024*1024;
const fileSchema=z.object({id:z.string().uuid(),filename:z.string().min(1).max(160),content_type:z.string(),size:z.number().int().positive().max(4194304),base64:z.string().max(5600000),sha256:z.string().regex(/^[a-f0-9]{64}$/)});
export const backupSchema=z.object({version:z.literal(2),exportedAt:z.string(),profile:profileInput,entries:z.array(entryInput).max(10000),assets:z.array(fileSchema).max(10000)});
export type Backup=z.infer<typeof backupSchema>;
export function decodeFile(base64:string){let binary:string;try{binary=atob(base64)}catch{throw new Error('Invalid backup file encoding.')}if(btoa(binary)!==base64)throw new Error('Invalid backup file encoding.');return Uint8Array.from(binary,c=>c.charCodeAt(0))}
export async function checksum(bytes:Uint8Array){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes as BufferSource)),b=>b.toString(16).padStart(2,'0')).join('')}
export async function validateBackup(value:unknown){const backup=backupSchema.parse(value);const ids=new Set<string>();let size=0;for(const a of backup.assets){if(ids.has(a.id))throw new Error('Backup contains duplicate file IDs.');ids.add(a.id);const bytes=decodeFile(a.base64);size+=bytes.length;if(size>MAX_BACKUP_BYTES)throw new Error('Backup exceeds 64 MB.');const inspected=inspectUpload(a.filename,bytes);if(bytes.length!==a.size||inspected.type!==a.content_type||await checksum(bytes)!==a.sha256)throw new Error('Backup file failed integrity validation: '+a.filename)}for(const e of backup.entries){const sources=[e.body,e.coverUrl,e.credentialUrl,...e.attachments.map(a=>a.url)].join('\n');for(const match of sources.matchAll(/\/api\/media\/([a-f0-9-]{36})/g))if(!ids.has(match[1]))throw new Error('Backup is missing a referenced file.')}return backup}
export function restoreEntry(entry:Backup['entries'][number],ids:Map<string,string>,suffix:string){const rewrite=(value:string)=>value.replace(/\/api\/media\/([a-f0-9-]{36})/g,(all,id)=>ids.has(id)?'/api/media/'+ids.get(id):all);return entryInput.parse({...entry,id:undefined,revision:0,status:'draft',slug:entry.slug.slice(0,110).replace(/-$/,'')+'-restored-'+suffix,body:rewrite(entry.body),coverUrl:rewrite(entry.coverUrl),credentialUrl:rewrite(entry.credentialUrl),attachments:entry.attachments.map(a=>({...a,url:rewrite(a.url)}))})}
