import {z} from 'zod';
import {parseRichDocument} from './rich-content';
import {kinds,validContentUrl} from './content';
const contentUrl=z.string().max(2000).refine(validContentUrl,'Use an uploaded file or a full HTTPS link.');
const date=z.string().refine(v=>v===''||(/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v),'Enter a valid date.');
const safeWebUrl=z.string().max(2000).refine(v=>!v||validContentUrl(v),'Use a full HTTPS link.');
type RichDocumentValue={type:'doc';content?:import('./content').RichNode[]};
export const richDocument=z.custom<RichDocumentValue>(value=>parseRichDocument(value)!==null,'Article content is invalid, too large, or deeply nested.');
export const articleSeo=z.object({title:z.string().max(180).default(''),description:z.string().max(320).default(''),canonicalUrl:safeWebUrl.default(''),socialImageUrl:contentUrl.default(''),openGraphTitle:z.string().max(180).default(''),openGraphDescription:z.string().max(320).default('')}).default({title:'',description:'',canonicalUrl:'',socialImageUrl:'',openGraphTitle:'',openGraphDescription:''});
export const entryInput=z.object({
 saveMode:z.enum(['draft','publish','unpublish']).optional(),id:z.string().uuid().optional(),revision:z.number().int().nonnegative().default(0),kind:z.enum(kinds),title:z.string().trim().min(1,'Add a title.').max(180),slug:z.string().trim().min(1,'Add a URL slug.').max(140).regex(/^[\p{L}\p{N}]+(?:-[\p{L}\p{N}]+)*$/u,'Use letters, numbers, and single hyphens.'),
 excerpt:z.string().max(800).default(''),body:z.string().max(160000).default(''),contentFormat:z.enum(['markdown','rich']).default('markdown'),richContent:richDocument.nullable().default(null),author:z.string().trim().max(100).default('Basel Alghamdi'),seo:articleSeo,category:z.string().max(80).default(''),status:z.enum(['draft','published']).default('draft'),featured:z.boolean().default(false),coverUrl:contentUrl.default(''),coverAlt:z.string().max(220).default(''),issuer:z.string().max(180).default(''),credentialUrl:contentUrl.default(''),date:date.default(''),sortOrder:z.number().int().min(0).max(9999).default(0),tags:z.array(z.string().trim().min(1).max(50)).max(15).default([]),attachments:z.array(z.object({url:contentUrl.refine(v=>!!v,'Add a download URL.'),name:z.string().min(1).max(180),format:z.string().max(20)})).max(10).default([])
}).superRefine((d,ctx)=>{if(d.contentFormat==='rich'&&!parseRichDocument(d.richContent))ctx.addIssue({code:'custom',path:['richContent'],message:'Article content contains an unsupported or invalid block.'});const publishing=d.saveMode==='publish'||(!d.saveMode&&d.status==='published');if(publishing&&d.coverUrl&&!d.coverAlt.trim())ctx.addIssue({code:'custom',path:['coverAlt'],message:'Describe the cover image for accessibility.'});if(d.kind==='article'&&publishing&&d.contentFormat==='markdown'&&!d.body.trim())ctx.addIssue({code:'custom',path:['body'],message:'Add article content before publishing.'});if(d.kind==='article'&&publishing&&d.contentFormat==='rich'&&(!d.richContent||!hasContent(d.richContent)))ctx.addIssue({code:'custom',path:['richContent'],message:'Add article content before publishing.'})});
export const profileInput=z.object({revision:z.number().int().nonnegative().default(0),name:z.string().trim().min(1).max(100),intro:z.string().max(500),bio:z.string().max(8000),university:z.string().max(180),degree:z.string().max(180),faculty:z.string().max(180),gpa:z.string().max(30),location:z.string().max(180),email:z.string().email(),linkedin:z.string().url().refine(v=>{try{const u=new URL(v);return u.protocol==='https:'&&['linkedin.com','www.linkedin.com'].includes(u.hostname)}catch{return false}},'Enter a LinkedIn HTTPS profile URL.'),interests:z.array(z.string().max(100)).max(12)});

function hasContent(node:import('./content').RichNode):boolean{return !!node.text?.trim()||['image','gallery','equation','mathInline','mathBlock','inlineMath','blockMath','video','audio','embed','table'].includes(node.type||'')||(node.content||[]).some(hasContent)}
