import {pageMetadata} from '@/lib/server/seo';
import Link from 'next/link';import {notFound} from 'next/navigation';import {getPublishedEntry,getProfile} from '@/lib/server/data';import {renderMarkdown} from '@/lib/markdown';import {displayDate,readTime} from '@/lib/content';import {ArticleTools,ReadingProgress} from '@/components/article-tools';import {RichContent,RichTableOfContents} from '@/components/rich-content';import {parseRichDocument,richOutline,richWordCount} from '@/lib/rich-content';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){
 const e=await getPublishedEntry('article',(await params).slug);if(!e)return{title:'Not found',robots:{index:false,follow:false}};
 const seo=e.seo;const title=seo?.title||e.title;const description=seo?.description||e.excerpt;const metadata=pageMetadata('/research/'+encodeURIComponent(e.slug),title,description,seo?.socialImageUrl||e.coverUrl);
 if(seo?.canonicalUrl&&/^https:\/\//.test(seo.canonicalUrl))metadata.alternates={canonical:seo.canonicalUrl};
 metadata.openGraph={...metadata.openGraph,type:'article',title:seo?.openGraphTitle||title,description:seo?.openGraphDescription||description,publishedTime:e.date||e.createdAt,modifiedTime:e.updatedAt,authors:[e.author||'Basel Alghamdi'],tags:e.tags};return metadata;
}
export default async function Article({params}:{params:Promise<{slug:string}>}){const a=await getPublishedEntry('article',(await params).slug);if(!a)notFound();const p=await getProfile();const rich=a.contentFormat==='rich'?parseRichDocument(a.richContent):null;const legacy=rich?null:renderMarkdown(a.body);const toc=rich?richOutline(rich).toc:legacy!.toc;const minutes=rich?Math.max(1,Math.ceil(richWordCount(rich)/230)):readTime(a.body);return <main id="main-content" className="wrap"><ReadingProgress/><header className="article-heading"><nav className="breadcrumb"><Link href="/research">Research</Link><span>/</span><span>{a.category}</span></nav><p className="eyebrow">{a.category}</p><h1>{a.title}</h1><p className="lead">{a.excerpt}</p><div className="byline"><div>{a.author||p.name}<small>{displayDate(a.date)} · {minutes} min read{a.updatedAt&&a.updatedAt.slice(0,10)!==a.date&&<> · Updated {displayDate(a.updatedAt)}</>}</small></div></div><ArticleTools file={'/api/research/'+encodeURIComponent(a.slug)+'/download'} label="Download article"/></header>{a.coverUrl&&<figure className="article-hero"><img className="cover-photo" src={a.coverUrl} alt={a.coverAlt}/></figure>}<div className="article-layout">{toc.length>0?<aside className="article-toc"><p>IN THIS ARTICLE</p>{rich?<RichTableOfContents items={toc}/>:<nav aria-label="In this article">{toc.map(t=><a href={'#'+encodeURIComponent(t.id)} key={t.id}>{t.label}</a>)}</nav>}</aside>:<div/>}<article id="article-content" className="article-body" dir="auto">{rich?<RichContent document={rich}/>:<div dangerouslySetInnerHTML={{__html:legacy!.html}}/>}{a.attachments.length>0&&<section><h2>Supporting files</h2>{a.attachments.map(f=><p key={f.url}><a href={f.url.startsWith('/api/media/')?f.url+'?download=1':f.url}>{f.name} ({f.format})</a></p>)}</section>}<div className="article-end"><p>Finance research, projects, and ideas.</p><Link href="/research">Back to the journal</Link></div></article></div></main>}
